#!/usr/bin/env bash
# End-to-end CLI smoke against a LOCAL Worker (issue #121): the local twin of
# scripts/deploy/smoke.sh. It boots the real Worker with wrangler, seeds the
# smoke-test workspace into the local D1, mints a session with the real
# `mint_session` example, then drives the real `livingbrain` binary through
# its write/read commands against http://127.0.0.1:8787 and asserts the
# outputs.
#
#   scripts/dev/cli-smoke.sh
#
# Everything is local: `wrangler dev` simulates D1/R2/KV, and the session is
# minted on this machine — no Cloudflare account, no deployed URL. First boot
# compiles the Worker to wasm (a release cargo build), which can take several
# minutes; later boots reuse `build/`.
#
# Secrets: `crates/livingbrain-venture/.dev.vars` is gitignored. When it is
# absent this script GENERATES it — HARNESS_SECRET, HARNESS_KEK_CURRENT,
# HARNESS_KEK_V1 — with openssl, and prints a notice (never a value). When
# it exists, the values in it are used as-is; the script only ever reads the
# names it needs. Values are never echoed.
#
# Any failed step prints PASS/FAIL with the observed status (and the
# response body on failure — problem+json, safe to show) and the script
# exits non-zero at the end.
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(cd -- "$script_dir/../.." && pwd)
venture_dir="$repo_root/crates/livingbrain-venture"
dev_vars="$venture_dir/.dev.vars"
# cli_bin is resolved after `cargo build`, from cargo's own target directory.

api=http://127.0.0.1:8787
workspace_id=T0SMOKETEST
user_id=U0SMOKETEST
# The cookie `mint_session` mints; `SESSION_COOKIE` in the workspaces module.
session_cookie_name=__Host-lb_session
export_out=/tmp/lb-smoke-export.zip
# First boot compiles the Worker (release wasm); give it five minutes.
boot_timeout_secs=300

# wrangler 4, not 3: the composition names a Workers Rate Limiting binding,
# and the runtime refuses every /v1/* request — in every environment, fail
# closed (cratefield-runtime-cloudflare issue #562) — when that binding does
# not resolve. wrangler 3.114's bundled workerd predates the binding, so a
# wrangler-3 run answers 503 before any route is reached. v4's local runtime
# provides the binding; its `dev` is local-only by design, so there is no
# --local flag on it (the d1 commands keep theirs).
wrangler=(npx --yes wrangler@4)

tmp_dir=$(mktemp -d)
wrangler_pid=
failures=0
trap 'rm -rf "$tmp_dir"; [ -n "$wrangler_pid" ] && kill -- -"$wrangler_pid" 2>/dev/null || true' EXIT

say()  { echo "cli-smoke: $*"; }
pass() { echo "PASS: $*"; }
# A soft failure: recorded, the run continues, the exit code reports it.
soft_fail() {
  failures=$((failures + 1))
  echo "FAIL: $*" >&2
}
die() { echo "cli-smoke: FAILED: $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1. Preflight: the tools this script drives.
# ---------------------------------------------------------------------------
for tool in node npx cargo curl python3 unzip openssl; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is not on PATH; the smoke test needs it"
done
[ -d "$venture_dir" ] || die "missing $venture_dir (run from a checkout)"
cd -- "$venture_dir"

# ---------------------------------------------------------------------------
# 2. `.dev.vars` — generate the dev secrets when absent, read them back
#    without printing them.
# ---------------------------------------------------------------------------
# HARNESS_SECRET: the `Signer` key, a raw string of at least 32 bytes
# (cratefield-core signer.rs MIN_SECRET_BYTES) — hex text is fine.
# HARNESS_KEK_CURRENT: the decimal KEK version that wraps (1..1024).
# HARNESS_KEK_V1: standard base64 of exactly 32 key bytes
# (cratefield-kms worker_secret.rs). MODEL_KEYS_SECRET is optional and left
# unset: without it the reads answer and a model connect 500s, which no
# step here does. ENV=staging is a SECRET here on purpose: EnvConfig reads
# secrets before vars, so it overrides wrangler.toml's `[vars] ENV =
# "production"` — a production ENV would arm the readiness gate, which
# refuses every /v1 route while the local run has no captcha secret.
generate_dev_vars() {
  local secret kek
  secret=$(openssl rand -hex 32) || die "openssl could not generate HARNESS_SECRET"
  kek=$(openssl rand -base64 32) || die "openssl could not generate HARNESS_KEK_V1"
  umask 077
  cat >"$dev_vars" <<VARS
# Generated by scripts/dev/cli-smoke.sh — local development secrets only.
# Gitignored; never commit this file. Delete it to get fresh values.
HARNESS_SECRET = "$secret"
HARNESS_KEK_CURRENT = "1"
HARNESS_KEK_V1 = "$kek"
# MODEL_KEYS_SECRET is optional (models module): uncomment to let a model
# connect store a provider key.
# MODEL_KEYS_SECRET = "<openssl rand -base64 32>"
ENV = "staging"
VARS
  umask 022
  echo "cli-smoke: wrote generated dev secrets to ${dev_vars#$repo_root/} (values not shown)"
}

dev_var() { # the value of one KEY in .dev.vars, or "" — never printed
  sed -n "s/^$1[[:space:]]*=[[:space:]]*\"\?\\([^\"]*\\)\"\?;*$/\\1/p" "$dev_vars" | tail -n 1
}

if [ ! -f "$dev_vars" ]; then
  generate_dev_vars
else
  say "$dev_vars exists; using the values in it (not shown)"
fi
# A .dev.vars that is not gitignored is one `git add -f` away from a leak.
git -C "$repo_root" check-ignore -q "$dev_vars" \
  || die "$dev_vars is not gitignored; refusing to put secrets next to a repo that would track it"

harness_secret=$(dev_var HARNESS_SECRET)
[ "${#harness_secret}" -ge 32 ] || die "HARNESS_SECRET in .dev.vars is shorter than 32 bytes"
[ "$(dev_var HARNESS_KEK_CURRENT)" = "1" ] || die "HARNESS_KEK_CURRENT must be 1 for a generated ring"
printf '%s' "$(dev_var HARNESS_KEK_V1)" | openssl base64 -d -A 2>/dev/null | wc -c | grep -qx 32 \
  || die "HARNESS_KEK_V1 in .dev.vars is not standard base64 of 32 bytes"
env_name=$(dev_var ENV)
[ "$env_name" = "staging" ] || die "ENV in .dev.vars must be staging (mint and worker must agree)"

# ---------------------------------------------------------------------------
# 3. D1 migrations (local simulated database).
# ---------------------------------------------------------------------------
say "applying D1 migrations (wrangler d1 migrations apply --local)"
"${wrangler[@]}" d1 migrations apply livingbrain --local >/dev/null 2>&1 \
  || die "d1 migrations apply failed; run it by hand in $venture_dir to see why"
pass "D1 migrations applied"

# ---------------------------------------------------------------------------
# 4. Seed the local D1 with the smoke-test workspace + member, mirroring
#    scripts/deploy/seed-staging.sql (idempotent, so re-runs are safe).
# ---------------------------------------------------------------------------
seed_sql="$tmp_dir/seed-local.sql"
cat >"$seed_sql" <<SQL
-- The local twin of scripts/deploy/seed-staging.sql: the workspace and the
-- member the CLI smoke signs in as. Both statements are idempotent.
INSERT INTO workspaces (id, name, owner_id, created_at)
VALUES ('$workspace_id', 'Smoke Test', '$user_id', '2026-01-01T00:00:00Z')
ON CONFLICT (id) DO NOTHING;

INSERT INTO workspace_members (workspace_id, user_id, name, timezone, is_admin, updated_at)
VALUES ('$workspace_id', '$user_id', 'Smoke Test', NULL, 0, '2026-01-01T00:00:00Z')
ON CONFLICT (workspace_id, user_id) DO NOTHING;
SQL
"${wrangler[@]}" d1 execute livingbrain --local --file "$seed_sql" >/dev/null 2>&1 \
  || die "seeding the local D1 failed"
seeded=$("${wrangler[@]}" d1 execute livingbrain --local --json \
  --command "SELECT id FROM workspaces WHERE id = '$workspace_id'" 2>/dev/null \
  | python3 -c 'import json,sys; rows=json.load(sys.stdin); print(sum(len(r["results"]) for r in rows))') \
  || die "could not read the seeded workspace back from the local D1"
[ "$seeded" = "1" ] || die "the seed did not stick: $seeded rows for $workspace_id"
pass "local D1 seeded with $workspace_id/$user_id"

# ---------------------------------------------------------------------------
# 5. Boot the Worker with wrangler dev, then wait for /__health.
# ---------------------------------------------------------------------------
if curl -sS --max-time 2 -o /dev/null "$api/__health" 2>/dev/null; then
  die "something already answers on $api — is another wrangler dev running?"
fi

say "starting wrangler dev (first boot compiles the Worker to wasm — this can take minutes)"
setsid env CI=true WRANGLER_SEND_METRICS=false \
  "${wrangler[@]}" dev --ip 127.0.0.1 --port 8787 \
  >"$tmp_dir/wrangler.log" 2>&1 &
wrangler_pid=$!

health_code=000
deadline=$((SECONDS + boot_timeout_secs))
until health_code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 2 "$api/__health" 2>/dev/null) &&
  [ "$health_code" = "200" ]; do
  kill -0 "$wrangler_pid" 2>/dev/null || {
    echo "--- last 40 lines of wrangler output ---" >&2
    tail -n 40 "$tmp_dir/wrangler.log" >&2
    die "wrangler dev exited before answering /__health"
  }
  if [ "$SECONDS" -ge "$deadline" ]; then
    echo "--- last 40 lines of wrangler output ---" >&2
    tail -n 40 "$tmp_dir/wrangler.log" >&2
    die "/__health did not answer 200 within ${boot_timeout_secs}s"
  fi
  sleep 2
done
pass "worker is up: GET $api/__health -> 200"

# ---------------------------------------------------------------------------
# 6. Mint a session with the real `mint_session` example.
# ---------------------------------------------------------------------------
say "minting a session cookie (ENV=staging, HARNESS_SECRET from .dev.vars)"
cookie=$(cd -- "$repo_root" && \
  HARNESS_SECRET="$harness_secret" ENV="$env_name" \
  cargo run -q -p livingbrain-workspaces --example mint_session) \
  || die "could not mint a session cookie"
[ -n "$cookie" ] || die "mint_session printed nothing"
# RFC 6265 cookie-octets (the same set venture lib.rs `is_cookie_octet` gates
# a bearer with, since the token is spliced into a Cookie header).
if ! printf '%s' "$cookie" | python3 -c '
import string, sys
allowed = set(string.ascii_letters + string.digits + "!#$%&()*+,-._^`|~")
sys.exit(1 if set(sys.stdin.read()) - allowed else 0)
'; then
  die "the minted token is not a cookie-octet string"
fi
pass "session minted (${#cookie} chars, value not shown)"

# ---------------------------------------------------------------------------
# 7. The strongest pre-routes proof: an EXISTING authed route answers the
#    minted session. Cookie first (what the web app sends), then Bearer
#    (what the CLI sends; SessionBearer splices a bearer into a cookie on
#    the surfaces that mount it).
# ---------------------------------------------------------------------------
me_url="$api/v1/workspaces/me"
me_body="$tmp_dir/me.json"
code=$(curl -sS -o "$me_body" -w '%{http_code}' --max-time 10 \
  --cookie "$session_cookie_name=$cookie" "$me_url") || code=000
if [ "$code" = "200" ]; then
  resolved=$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("workspace",{}).get("id",""))' \
    <"$me_body" 2>/dev/null || echo "")
  [ "$resolved" = "$workspace_id" ] \
    && pass "auth (cookie): GET $me_url -> 200, workspace.id=$resolved" \
    || soft_fail "auth (cookie): 200 but workspace.id=$resolved, expected $workspace_id"
else
  soft_fail "auth (cookie): GET $me_url -> $code, expected 200; body: $(cat "$me_body")"
fi

code=$(curl -sS -o "$me_body" -w '%{http_code}' --max-time 10 \
  -H "Authorization: Bearer $cookie" "$me_url") || code=000
if [ "$code" = "200" ]; then
  pass "auth (bearer): GET $me_url -> 200"
else
  # Expected today: the workspaces routes read the session cookie only; the
  # bearer-splicing SessionBearer is mounted on the pages module's /mcp
  # surface (venture lib.rs), where the same minted token answers an MCP
  # tools/call and a bad one is refused 401 mcp/unauthorized — proven during
  # this script's bring-up. When the CLI routes land they mount the same
  # bearer auth, and this check should turn 200.
  echo "NOTE: auth (bearer): GET $me_url -> $code (the workspaces routes read the cookie only; body: $(cat "$me_body"))"
fi

# ---------------------------------------------------------------------------
# 8. Drive the real CLI. Every step is asserted on the shape the CLI's own
#    --json contract names (crates/livingbrain-cli/src/api.rs). Until the
#    new routes land these 404, which is a FAIL here on purpose: when the
#    routes merge, only this section decides green.
# ---------------------------------------------------------------------------
cargo build -q -p livingbrain-cli --bin livingbrain \
  || die "could not build the livingbrain CLI"
# Where cargo put it — CARGO_TARGET_DIR may move it out of the workspace.
target_dir=$(cargo metadata --format-version 1 --no-deps 2>/dev/null \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["target_directory"])') \
  || die "could not read cargo's target directory"
cli_bin="$target_dir/debug/livingbrain"
[ -x "$cli_bin" ] || die "the CLI binary is missing at $cli_bin"
cli() { # run the CLI; stdout to cli_out, exit code to cli_code, stderr to cli_err
  cli_err="$tmp_dir/cli.err"
  if cli_out=$(LIVINGBRAIN_API_URL="$api" LIVINGBRAIN_TOKEN="$cookie" "$cli_bin" "$@" 2>"$cli_err"); then
    cli_code=0
  else
    cli_code=$?
  fi
}
cli_json() { # cli_json EXPR — run python over the last cli_out
  printf '%s' "$cli_out" | python3 -c "$1" 2>/dev/null
}

note_text="smoke test note $(date -u +%Y-%m-%dT%H:%M:%SZ)"
note_id=""
say "CLI: livingbrain note \"$note_text\" --json"
cli note "$note_text" --json
if [ "$cli_code" = 0 ]; then
  note_id=$(cli_json 'import json,sys; print(json.load(sys.stdin).get("id",""))') || note_id=""
  [ -n "$note_id" ] && pass "note -> 200, id present" \
    || soft_fail "note -> 200 but no id in: $cli_out"
else
  soft_fail "note -> exit $cli_code, expected 0; body: $(cat "$cli_err") $cli_out"
fi
# The note id is "<scope>/<slug>"; the page route wants the slug.
slug=${note_id#scope/}
slug=${slug##*/}

say "CLI: livingbrain search smoke --json"
cli search smoke --json
if [ "$cli_code" = 0 ]; then
  if [ -z "$note_id" ] && [ -z "$slug" ]; then
    soft_fail "search -> 200 but the note failed, so there is nothing to find: $cli_out"
  elif printf '%s' "$cli_out" | SLUG="$slug" NOTE_ID="$note_id" python3 -c '
import json, os, sys
results = json.load(sys.stdin).get("results", [])
needle = os.environ["NOTE_ID"] or os.environ["SLUG"]
sys.exit(0 if results and needle in json.dumps(results) else 1)
'; then
    pass "search -> 200, the note is in results"
  else
    soft_fail "search -> 200 but the note is not in results: $cli_out"
  fi
else
  soft_fail "search -> exit $cli_code, expected 0; body: $(cat "$cli_err") $cli_out"
fi

say "CLI: livingbrain page $slug --json"
cli page "$slug" --json
if [ "$cli_code" = 0 ] && [ -n "$(cli_json 'import json,sys; print(json.load(sys.stdin).get("markdown",""))')" ]; then
  pass "page -> 200, markdown present"
else
  soft_fail "page -> exit $cli_code, expected 0 with markdown; body: $(cat "$cli_err") $cli_out"
fi

say "CLI: livingbrain ask \"what did we note about smoke?\" --json"
cli ask "what did we note about smoke?" --json
if [ "$cli_code" = 0 ] \
  && cli_json 'import json,sys; d=json.load(sys.stdin); sys.exit(0 if d.get("answer") and isinstance(d.get("citations"), list) else 1)'; then
  pass "ask -> 200, answer + citations present"
else
  soft_fail "ask -> exit $cli_code, expected 0 with answer+citations; body: $(cat "$cli_err") $cli_out"
fi

say "CLI: livingbrain export --out $export_out --force"
rm -f "$export_out"
cli export --out "$export_out" --force
if [ "$cli_code" = 0 ] && [ -s "$export_out" ] && unzip -tqq "$export_out" >/dev/null 2>&1; then
  listing=$(unzip -l "$export_out")
  if [ -n "$slug" ] && printf '%s' "$listing" | grep -Fq "$slug.md"; then
    pass "export -> 2xx zip, lists $slug.md"
  elif printf '%s' "$listing" | grep -q '\.md'; then
    pass "export -> 2xx zip, lists markdown entries"
  else
    soft_fail "export -> 2xx zip but no .md inside: $listing"
  fi
else
  soft_fail "export -> exit $cli_code or not a valid zip; body: $(cat "$cli_err") $cli_out"
fi

# ---------------------------------------------------------------------------
# 9. Web-contract spot checks: PUT /v1/pages/{slug} create, update, and a
#    stale base_version conflict (the wiki.html contract, app/README.md).
# ---------------------------------------------------------------------------
put_page() { # put_page JSON -> status in page_code, body in page_body
  page_body="$tmp_dir/page.json"
  page_code=$(curl -sS -o "$page_body" -w '%{http_code}' --max-time 10 \
    -X PUT "$api/v1/pages/smoke-page" \
    -H "Authorization: Bearer $cookie" -H 'Content-Type: application/json' \
    -d "$1") || page_code=000
}

put_page '{"markdown":"# hi","base_version":null,"title":"Smoke"}'
if [ "$page_code" = "200" ] \
  && [ "$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("version",""))' <"$page_body" 2>/dev/null)" = "1" ]; then
  pass "pages PUT (create, base_version=null) -> 200 version 1"
else
  soft_fail "pages PUT (create) -> $page_code, expected 200 version 1; body: $(cat "$page_body")"
fi

put_page '{"markdown":"# hi2","base_version":1,"title":"Smoke"}'
if [ "$page_code" = "200" ] \
  && [ "$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("version",""))' <"$page_body" 2>/dev/null)" = "2" ]; then
  pass "pages PUT (update, base_version=1) -> 200 version 2"
else
  soft_fail "pages PUT (update) -> $page_code, expected 200 version 2; body: $(cat "$page_body")"
fi

put_page '{"markdown":"# hi3","base_version":1,"title":"Smoke"}'
if [ "$page_code" = "409" ]; then
  pass "pages PUT (stale base_version=1) -> 409 conflict"
else
  soft_fail "pages PUT (stale) -> $page_code, expected 409; body: $(cat "$page_body")"
fi

# ---------------------------------------------------------------------------
# Summary.
# ---------------------------------------------------------------------------
if [ "$failures" -eq 0 ]; then
  say "ok: every step passed"
else
  say "$failures step(s) failed"
fi
exit "$failures"
