// The vendored provider catalog, and the script that writes it.
//
// `app/assets/providers.json` is generated by `scripts/sync-providers` from
// Colonizer's `web/src/providerCatalog.ts`. These tests fail when the file is
// malformed — a hand edit, a bad merge, an upstream shape the parser
// half-read — before the server (`include_str!`) or the page imports it.

import test from "node:test";
import assert from "node:assert/strict";

import catalog from "../assets/providers.json" with { type: "json" };
import { parseCatalog, validateEntries } from "../../scripts/sync-providers.mjs";

test("the vendored catalog is well formed", () => {
  assert.ok(Array.isArray(catalog._comment) && catalog._comment.join(" ").includes("GENERATED"));
  assert.equal(catalog.source.repo, "Colonizer-dev/harness");
  assert.equal(catalog.source.path, "web/src/providerCatalog.ts");
  assert.match(catalog.source.commit, /^[0-9a-f]{40}$/, "pinned to a commit");
  assert.ok(
    catalog._comment.some((line) => line.includes(catalog.source.commit)),
    "the header names the commit",
  );
  validateEntries(catalog.builtin, "builtin");
  validateEntries(catalog.providers, "providers");
  assert.ok(catalog.providers.length > 50, `${catalog.providers.length} providers`);
  const ids = [...catalog.builtin, ...catalog.providers].map((p) => p.id);
  assert.equal(new Set(ids).size, ids.length, "ids are unique across both lists");
  assert.ok(!ids.includes("custom"), "custom is not a catalog id");
  // Both wires and both auth styles are represented, which is what the
  // server's probe has to speak.
  const all = [...catalog.builtin, ...catalog.providers];
  for (const wire of ["anthropic", "openai"]) assert.ok(all.some((p) => p.wire === wire), wire);
  for (const auth of ["bearer", "x-api-key"]) assert.ok(all.some((p) => p.auth === auth), auth);
});

test("the validator refuses each way an entry can be malformed", () => {
  const good = {
    id: "ok",
    name: "OK",
    base_url: "https://api.example.com",
    auth: "bearer",
    wire: "anthropic",
    site: "https://example.com",
  };
  assert.doesNotThrow(() => validateEntries([good]));
  const bad = [
    [{ ...good, id: "Has Space" }, /bad id/],
    [{ ...good, base_url: "http://api.example.com" }, /https/],
    [{ ...good, auth: "basic" }, /auth/],
    [{ ...good, wire: "gemini" }, /wire/],
    [{ ...good, site: "javascript:alert(1)" }, /site/],
    [{ ...good, base_url: "https://h.example/${ID}" }, /variables/],
    [{ ...good, models: [""] }, /models/],
    [{ ...good, context_tokens: -1 }, /context_tokens/],
    [{ ...good, extra: 1 }, /unexpected field/],
  ];
  for (const [entry, message] of bad) {
    assert.throws(() => validateEntries([entry]), message, JSON.stringify(entry));
  }
  assert.throws(() => validateEntries([good, good]), /duplicate/);
  assert.throws(() => validateEntries([]), /empty/);
});

test("the upstream TypeScript is parsed as data, never run", () => {
  const ts = `
    export const PROVIDER_CATALOG: CatalogEntry[] = [
      { id: "a", name: "A", base_url: "https://a.example/\${ID}/x", auth: "x-api-key", wire: "anthropic", site: "https://a.example", variables: [{ name: "ID", label: "Id", placeholder: "ep-1" }], context_tokens: 1_048_576 },
      // a comment between entries
      { id: "b", name: "B, with: punctuation", base_url: "https://b.example/v1", auth: "bearer", wire: "openai", site: "" },
    ];
  `;
  const parsed = parseCatalog(ts);
  assert.equal(parsed.length, 2);
  assert.equal(parsed[0].context_tokens, 1048576);
  assert.equal(parsed[1].name, "B, with: punctuation");
  validateEntries(parsed);
  assert.throws(() => parseCatalog("export const OTHER = [];"), /not found/);
  assert.throws(() => parseCatalog("PROVIDER_CATALOG = [ { id: f() } \n];"));
});
